#  handlers/main.py  - kla app main webapp request handlers
#
#
__author__ = 'johnw'

import logging, json

from flask import (Flask, request, session, g, redirect, url_for,
     abort, render_template)

import settings

log = logging.getLogger('handlers.main')

# instantiate Flask (global) app
kla = Flask('app', **settings.FLASK.app)

def run_dev_server():
    "launch Flask dev server"
    kla.run(**settings.FLASK.run)

# -------- main request handlers --------

@kla.route('/')
def index():
    #
    #  test parseTree
    from parser.parse import Parser
    from parser.patterns.clientLog import patternDef
    import os
    #
    p = Parser(os.path.expanduser("~/Dropbox/Documents/Kontiki 2014/debugging/Lloyds/pDPTu3_AT2k1-20151125-204429/error2.log"), patternDef)
    p.parse()
    #

    def _mergeTableData(child, labelIndexes, labels, rows):
        "merges child labels & row into parent labels & rows"
        newLabels = set(child['labels']) - set(labels)
        for k in sorted(newLabels):
            labelIndexes[k] = len(labels)
            labels.append(k)
        row = [''] * len(labels)
        for i, k in enumerate(child['labels']):
            row[labelIndexes[k]] = child['rows'][0][i]
        rows.append(row)

    def _renderParseTree(name, level):
        "recursive parseTree-to-jsTree data renderer"
        labelIndexes = {}
        children, labels, row = [], [], []
        rows = [row]
        if isinstance(level, dict):
            # first pass for leaf values
            keys = set(level.keys())
            for k in sorted(keys):
                v = level[k]
                if isinstance(v, (dict, list)):
                    continue
                else:
                    labelIndexes[k] = len(labels)
                    labels.append(k)
                    row.append(v)
                    keys.remove(k)
            # second pass for non-leafs
            for k in sorted(keys):
                v = level[k]
                child = _renderParseTree(k, v)
                if len(row) == 0 and len(child['rows']) == 1:
                    # no leaf-values at this level, accumulate any immediate child singleton rows into my row vector
                    _mergeTableData(child, labelIndexes, labels, rows)
                children.append(child)
            #
        else: # list
            for v in level:
                # list top-level values always dicts
                timestamp = v.get('timestamp')
                child = _renderParseTree(timestamp, v)
                if len(child['rows']) == 1:
                    # no leaf-values at this level, accumulate any immediate child singleton rows into my row vector
                    _mergeTableData(child, labelIndexes, labels, rows)
                children.append(child)

        # build node for this level
        node = dict(text=name, labels=labels, rows=rows)
        if children:
            node['children'] = children
        #
        return node

    # top-level jsTree roots are children of the top-level parseTree
    renderedTree = _renderParseTree('top', p.parseTree)['children']

    return render_template("index.html",
                           renderedParseTree=json.dumps(renderedTree))


#     'core' : {
#         'data' : [
#                 {
#                   id          : "string" // will be autogenerated if omitted
#                   text        : "string" // node text
#                   icon        : "string" // string for custom
#                   state       : {
#                     opened    : boolean  // is the node open
#                     disabled  : boolean  // is the node disabled
#                     selected  : boolean  // is the node selected
#                   },
#                   children    : []  // array of strings or objects
#                   li_attr     : {}  // attributes for the generated LI node
#                   a_attr      : {}  // attributes for the generated A node
#                 }#         ]
#     }
# });

